### ISSUE TITLE
Error 'x509: certificate has expired or is not yet valid' while running './loophole http <port>' command

### ISSUE THREAD

**Issue by RahulSDeshpande** [loophole/cli#137]
**Describe the bug**
Error `x509: certificate has expired or is not yet valid` is thrown while running `./loophole http <port>` command.

**To Reproduce**
1. Run this command
```bash
./loophole http 8080
Loophole - End to end TLS encrypted TCP communication between you and your clients

Registering your domain... Error! Post "https://api.loophole.cloud:443/api/site": x509: certificate has expired or is not yet valid: current time 2021-07-27T10:29:44+04:00 is after 2021-07-27T02:42:13Z
10:29AM ERR Something unexpected happened, please let developers know
10:29AM FTL Post "https://api.loophole.cloud:443/api/site": x509: certificate has expired or is not yet valid: current time 2021-07-27T10:29:44+04:00 is after 2021-07-27T02:42:13Z
```

**Expected behavior**
Should generate link

**Environment**
 - OS: **Mac 11.2.3**
 - Version: **1.0.0-beta.14**

**Additional context**
This was working 2 hours ago, & stopped working since then.

**Comment by Morishiri** [comment]
Thanks for reporting the issue! Looking into it 👀

**Comment by Morishiri** [comment]
@RahulSDeshpande the issue should now be resolved. We had small trouble with our server certificate. Please confirm that it's working from your side.

**Comment by RahulSDeshpande** [comment]
@Morishiri 

Idealny!
It is working now.

Thanks 😎

**Comment by nober47747474** [comment]
Registering your domain... Error! Post "https://api.loophole.cloud:443/api/site": x509: certificate has expired or is not yet valid:
7:05AM ERR Something unexpected happened, please let developers know
7:05AM FTL Post "https://api.loophole.cloud:443/api/site": x509: certificate has expired or is not yet valid:
Please help me figure it out, is this the only problem I have?
