### ISSUE TITLE
Certificate signed by unknown authority error

### ISSUE THREAD

**Issue by kensplanet** [loophole/cli#148]
**Describe the bug**
I am getting a certificate signed by unknown authority error. I am using self-signed certificates for my local application and am also on company VPN.

**To Reproduce**
```
./loophole http 8072
Loophole - End to end TLS encrypted TCP communication between you and your clients

Registering your domain... Error! Post "https://api.loophole.cloud:443/api/site": x509: certificate signed by unknown authority
10:41AM ERR Something unexpected happened, please let developers know
10:41AM FTL Post "https://api.loophole.cloud:443/api/site": x509: certificate signed by unknown authority
```

**Expected behavior**
Should show success logs

**Environment**
 - OS: Mac OS Catalina 
 - Version: v10.15.7

**Comment by Morishiri** [comment]
Looks like your computer doesn't trust our certificate.

According to e.g. digicert cert checker we are fine, you can check it yourself at 
https://www.digicert.com/help/

Please verify your settings.

**Comment by kensplanet** [comment]
Unfortunately, the local application will not work without VPN. I have been tasked by my company team to find the best tunnelling tool out there and even get paid licenses. I'll have to probably check other tools out there which will work behind VPN. You can close this ticket. But something to be investigated by the team as this is a very common use case of people using loophole from company VPN.

**Comment by Morishiri** [comment]
I asked you to try without VPN just to ensure the location of the issue.
We have worked with loophole behind VPN already and it works. It looks like the VPN you're using is somehow not trusting Let's Encrypt certificate which we are using.
