### ISSUE TITLE
Chrome/Chromium >=70 is required

### ISSUE THREAD

**Issue by msanaullahsahar** [loophole/cli#153]
Why I am unable to run loophole GUI in windows 11 with updated Microsoft edge installed? It is asking for Chrome/Chromium but as far as I know, Microsoft edge is technically a chromium based browser.
Note: I am on Microsoft Edge: Version 96.0.1054.62 (Official build) (64-bit).

**Comment by Morishiri** [comment]
The reason behind that is that we use https://github.com/zserge/lorca underneath to run the desktop version and that's the requirement of the underlying library.

The only thing I can promise is to update the underlying library and then the features may start working on your side.

Anyway I would recommend to install Chromium to be sure everything behaves as expected.

**Comment by msanaullahsahar** [comment]
Thanks @Morishiri for this explanation.
