### ISSUE TITLE
Error while starting a tunnel. Problem in decoding tokens.

### ISSUE THREAD

**Issue by msanaullahsahar** [loophole/cli#154]
sudo ./loophole http 80
Loophole - End to end TLS encrypted TCP communication between you and your clients

Registering your domain... Error! Request Error (401): There was a problem reading token - There was a problem decoding tokens: unexpected end of JSON input
8:12AM ERR Request ended with status code 401
8:12AM ERR There was a problem reading token
8:12AM ERR Details: There was a problem decoding tokens: unexpected end of JSON input
8:12AM ERR Please fix the above issue and try again
8:12AM FTL Request Error (401): There was a problem reading token - There was a problem decoding tokens: unexpected end of JSON input

**Comment by Morishiri** [comment]
Hello @msanaullahsahar,

does this problem happen each time you run the command or was it one-time issue?

**Comment by msanaullahsahar** [comment]
This happens every time when i run this command to create a tunnel. Previously it was working fine. Nothing has changed on the server.

OS: Raspbian OS (bullseye)
Loophole version: loophole-cli_1.0.0-beta.14_linux_armv7

**Comment by Morishiri** [comment]
Please try logging out:

```
loophole account logout
```

and then logging back in

```
loophole account login
```

and try starting up the tunnel again.

Additionally, I think you can abandon `sudo` in your command as we are not binding to any restricted ports.
