### ISSUE TITLE
Confirming that the client is open source?

### ISSUE THREAD

**Issue by anderspitman** [loophole/cli#155]
Hey, I was just looking to update the entry for Loophole in my list here:

https://github.com/anderspitman/awesome-tunneling

It looks like the entire client is MIT open source, is that correct?

Any plans for the server to be open source?

**Comment by 0x7f** [comment]
Hi @anderspitman, thanks for reaching out! Yes, the client is open source and stays open source (License is MIT as you stated). And yes, we are working a version of the backend we can open source as well. Stay tuned. For now, the backend is closed source.

**Comment by anderspitman** [comment]
Sorry forgot to respond and close this. Thanks!
