### ISSUE TITLE
Improve security by offering the possibility to disable older TLS ciphers

### ISSUE THREAD

**Issue by dariox86** [loophole/cli#162]
Currently I get a B rating on SSL Server Test by Qualys SSL Labs because TLS 1.0, 1.1 and ciphers with shorter keys are allowed.

**Comment by Morishiri** [comment]
Hello, I think it's actually cool idea, will investigate weather it will be possible to achieve with our current setup.

**Comment by Morishiri** [comment]
This was implemented, I tested and the score on the SSL Server Test by Qualys SSL Labs it scores A rank with ciphers disabled.

There is now an optional switch added to the serving commands:
```
--disable-old-ciphers          Disable TLS ciphers older than TLS1.2
```

Please mind that this version is still unreleased.
