### ISSUE TITLE
Occasional tunnel startup error: tcpip-forward request denied by peer

### ISSUE THREAD

**Issue by jonespm** [loophole/cli#189]
**Describe the bug**
Occasionally when starting loophole it stops with this error below. This has been happening for at least a few months. Not sure if it's this version or something else, but I didn't see any reports about this. 

```
Registering your domain... Success!
Starting local proxy server...  Success!
Initializing secure tunnel...  Success!
11:13AM ERR Listening on remote endpoint for HTTPS failed
11:13AM FTL Tunnel startup error error="ssh: tcpip-forward request denied by peer" tunnelId=56e0cd6b-90e0-43d7-bce1-3914cd3798f4
```

Running the command again often gets it working. I'd say this happens to me about 25-50% of the time. I've tried on both OSX and Linux and some of my co-workers also have this same issue. 

**To Reproduce**
1. Startup loophole
2. Notice the error

**Expected behavior**
Loophole should always connect or return a better error message for why it can't connect.

**Screenshots**
OSX
<img width="800" alt="image" src="https://user-images.githubusercontent.com/27447/190194933-0695d455-f732-4e6a-8e49-554dcc8ddf83.png">
Windows 11
![image](https://user-images.githubusercontent.com/27447/190197279-0c26ac10-e485-4c92-b1e0-9cd4d46926fc.png)

**Environment**
 - OS: OSX 12.5.1 (M1 and x86), Windows 11
 - Version loophole version 1.0.0-beta.15 (5cecf33)

**Additional context**
None

**Comment by ap1969** [comment]
I get the same thing on Windows, running v1.0.0-beta.15 (5cecf33) (also had it on beta.14), again for a few months now.

**Comment by ap1969** [comment]
Verbose logging:


C:\dev\>yarn loophole --verbose
yarn run v1.22.10
$ loophole http 8000 --hostname=<subdomain> --disable-proxy-error-page --verbose
Loophole - End to end TLS encrypted TCP communication between you and your clients


```9:00AM DBG Info response: {1.0.0-beta.15}
Registering your domain...
9:00AM DBG Site registration response: {<subdomain>.loophole.site}
9:00AM DBG Tunnel starting up...
Starting local TLS proxy server
9:00AM DBG Proxy via http to http://127.0.0.1:8000 created
Starting local proxy server...
9:00AM DBG Server for proxy created

9:00AM DBG Proxy listener for HTTPS started on port 54254

9:00AM DBG Started server TLS server
Initializing secure tunnel...
9:00AM DBG Dialing SSH Gateway for HTTPS succeeded
9:00AM ERR Listening on remote endpoint for HTTPS failed
9:00AM FTL Tunnel startup error error="ssh: tcpip-forward request denied by peer" tunnelId=3e802671-6f02-4b81-8ebc-ed7f0d59c64c
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by LFGKirsten** [comment]
Hi folks, not sure if there are any updates on this but I'm unable to use Loophole completely because of this issue. It's failing to start for me entirely even if i use the sample port 3000

L:\loophole-cli_1.0.0-beta.15_windows_64bit\loophole-cli_1.0.0-beta.15_windows_64bit
λ loophole http 3000
Loophole - End to end TLS encrypted TCP communication between you and your clients

Registering your domain... Success!
Starting local proxy server...  Success!
Initializing secure tunnel...  Success!
12:05PM ERR Listening on remote endpoint for HTTPS failed
12:05PM FTL Tunnel startup error error="ssh: tcpip-forward request denied by peer" tunnelId=58dcbf1c-6197-4494-9246-d0057cbd83ad

**Comment by MrAshRhodes** [comment]
This has changed now from "occasional" to every other time now. had to resort to other tools, bore, ngrok etc

**Comment by ap1969** [comment]
I've done the same. Now using Cloudflare tunnel. It's a shame, but given loophole was free, without the resources of Cloudflare, it was inevitale, I guess.

**Comment by Morishiri** [comment]
Hello, sorry for the lack of responses from our side. My notification settings were messed up and I didn't even receive any info about this issue 🙈

We are aware of this problem and we know the steps to mitigate it, but we lack a correct detection still. As given above, loophole is free and only maintained during some breaks at our regular jobs. Recently there is a lot of work outside loophole so the time dedicated to it is much smaller than at the beginning, but we will try to solve this once and for good soon.

Best regards and thank you for trying out loophole. I hope you'll be able to get back to it and use it again :)

**Comment by RedmattersBV** [comment]
At the moment I experience same problem, is there anything that I can do to fix this? @Morishiri

**Comment by psymbio** [comment]
Exact same problem on the WSL.

What steps can be taken?

**Comment by 0x7f** [comment]
Hey, sorry for the inconvenience. The backend system was stuck. Restarted it and it works again. We did not find time to fix this yet, as we are busy with other projects and have very little time for improving loophole at the moment. We will look into this as soon as possible, promised :)
