### ISSUE TITLE
Add DOS And/Or DDos Analysis Support

### ISSUE THREAD

**Issue by sancho1952007** [loophole/cli#198]
Hi there, I would love to see this feature that loophole will automatically analyse incomming requests and monitor the requests based on their IP. I want this feature because when I was benchmarking my server, my node server could handle the requests but loophole crashed

It was sending about 300 requests in 2.75 seconds

But, the loophole side of my server got crashed while my node server was handling these requests.

Also, if this suggestion is currently not possible, pease consider as a bug since it is very crucial that loophole server should not crash as the service that you provide will be down and the domain may be taken by someone else!

So, please consider this one...

**Comment by Morishiri** [comment]
Hello,

we will check the stability of the server under the load, but just to highlight:

> Also, if this suggestion is currently not possible, pease consider as a bug since it is very crucial that loophole server should not crash as the service that you provide will be down and the domain may be taken by someone else!

is not true, no-one can take your domain as it is being bound to your account.

**Comment by sancho1952007** [comment]
Ok 👍
