### ISSUE TITLE
Self hosting in future

### ISSUE THREAD

**Issue by amankalra172** [loophole/cli#20]
gateway-port and gateway-url  are two flags currently available in the loophole CLI version. They help us for the self hosting option. However, in the current beta version, we do not plan to have them. 

keeping that in mind,, We need to consider self-hosting as a service in the premium plan or as an individual service altogether. This provides more security and control for the user in future releases. 

For now, let's remove the gateway-url option & gateway-port  in the beta version.

**Comment by Morishiri** [comment]
Closing this for now, to be opened when there is a need
