### ISSUE TITLE
Loophole occasionally stops working or won't load

### ISSUE THREAD

**Issue by hafnerpw** [loophole/cli#200]
## CASE 1:
Loophole isn't able to start and the log stops after the 3rd message with "_Initializing secure tunnel...  Success!_" but no error message is shown and it loads for ever. 

LOG: 
```
PS C:\Users\**\Desktop\Loophole> .\loophole http 14042 --hostname mycustomname
Loophole - End to end TLS encrypted TCP communication between you and your clients

Registering your domain... Success!
Starting local proxy server...  Success!
Initializing secure tunnel...  Success!
```

## CASE 2

Loophole starts and does not reflect any problems, but the connection is not open and incoming requests are not recognized at all.

LOG:

```
PS C:\Users\**\Desktop\Loophole> .\loophole http 14042 --hostname mycustomname
Loophole - End to end TLS encrypted TCP communication between you and your clients

Registering your domain... Success!
Starting local proxy server...  Success!
Initializing secure tunnel...  Success!


Forwarding https://mycustomname.loophole.site -> http://127.0.0.1:14042
Press CTRL + C to stop the service
Logs:
8:59AM INF Awaiting connections...
8:59AM INF Succeeded to accept connection over HTTPS
8:59AM INF TLS Certificate successfully provisioned
```

**To Reproduce**
Unfortunatly this behavior occurs occasionally and I am not able to trace the cause of this issue properly. 
Restarting the PC does not help
Logging out and in to my loophole account also brings no help. 

**Expected behavior**
It should work 99% of the time or display a proper error message of what is causing this issue.

**Environment**
 - OS: Windows 10 Enterprise 
 - Version 1.0.0-beta.15 - tried desktop and CLI

**Additional context**
About 80% of the time it is working as expected, but once this behavior occurs I am not able to fix it. Most of the time it starts working again after a random timespan of a few hours.
I am switching quite often from my home connection to the office and therefore have to restart the loophole several times during the day, so maybe the problem is somehow related to that.

**Comment by Morishiri** [comment]
Should work again, please try it out now.

**Comment by hafnerpw** [comment]
Working again after a logout/login. Thanks but what was the issue? Can I avoid this somehow from my end ?

**Comment by Morishiri** [comment]
The issue is that sometimes the tunnel gets stuck, it's a known issue on our side. We will try to fix it, but recently we don't have so much development power to deal with it quickly.
