### ISSUE TITLE
https://www.buymeacoffee.com/loophole - 404

### ISSUE THREAD

**Issue by ogroppo** [loophole/cli#210]
<img width="632" alt="Screenshot 2023-02-08 at 21 34 22" src="https://user-images.githubusercontent.com/4820803/217656141-2b8fc483-7a92-444a-a81e-05017a3eb544.png">

**Comment by Morishiri** [comment]
Hello, yes - we resigned from buymeacoffee, because the complexity of handling that on the TAX side was bigger than the gain on that. We will think about different solutions we could use to let you support us. Stay tunned :)
