### ISSUE TITLE
lookup api.loophole.cloud: no such host

### ISSUE THREAD

**Issue by DarKWinGTM** [loophole/cli#218]
Registering your domain... Error! Post "https://api.loophole.cloud:443/api/site": dial tcp: lookup api.loophole.cloud: no such host
7:18PM ERR Something unexpected happened, please let developers know
7:18PM FTL Post "https://api.loophole.cloud:443/api/site": dial tcp: lookup api.loophole.cloud: no such host

**Comment by 0x7f** [comment]
Hey @DarKWinGTM, I was just trying whether enabling IPv6 in the loophole backend will break anything. And yes, it did. You were very quick to notice. I already reverted it and loophole should be working normal again. Can you confirm?

**Comment by 0x7f** [comment]
It might be that your DNS provider is caching the broken entries for a little longer. The TTL for the DNS record was set to just 1 minute and should be gone since ~15 minutes already. Can you try resolving `api.loophole.cloud` on your end?

```
% dig +short api.loophole.cloud 8.8.8.8
138.201.126.72
% curl https://api.loophole.cloud
{"version":"0.0.1"}%
```

**Comment by 0x7f** [comment]
Here the confirmation that loophole cli works for me:
```
% loophole path .
Loophole - End to end TLS encrypted TCP communication between you and your clients

There is new version available, to get it please visit https://github.com/loophole/cli/releases/tag/1.0.
Registering your domain... Success!
Starting local file server Success!
Starting local proxy server...  Success!
Initializing secure tunnel...  Success!


Forwarding https://REDACTED.loophole.site -> .
Press CTRL + C to stop the service
Logs:
1:33PM INF Awaiting connections...
1:33PM INF Succeeded to accept connection over HTTPS
1:33PM INF Succeeded to accept connection over HTTPS
1:33PM INF Succeeded to accept connection over HTTPS
1:33PM INF Succeeded to accept connection over HTTPS
```

**Comment by 0x7f** [comment]
@DarKWinGTM that's very strange that Google DNS (`8.8.8.8`) is not resolving it for you. Did it change in the meantime?

When using some website to resolve the endpoint, it works as well: https://dnschecker.org/all-dns-records-of-domain.php?query=api.loophole.cloud&rtype=ALL&dns=google (A record must be available for IPv4 to work and AAAA for IPv6 should not be set):

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/176090/224549628-ea9059e0-a92d-4386-9e00-4793dfc72fb5.png">

**Comment by 0x7f** [comment]
Hi @DarKWinGTM we had an issue with our servers and just fixed them. It should work again. Please let me know if you are still running into issues.

**Comment by Morishiri** [comment]
@DarKWinGTM please try again now. We had a node failure at night.

**Comment by 0x7f** [comment]
@DarKWinGTM which exact command did you use to start your tunnel? Will look into it and come back to you

**Comment by Morishiri** [comment]
@DarKWinGTM 500s should be gone now :)

**Comment by DarKWinGTM** [comment]
Initializing secure tunnel...  Error! ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
12:07PM INF SSH Connection failed, retrying in 10 seconds... (Attempt 1/5)
Initializing secure tunnel...  Error! ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
12:07PM INF SSH Connection failed, retrying in 10 seconds... (Attempt 2/5)

**Comment by DarKWinGTM** [comment]
Initializing secure tunnel...  Error! ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
10:10AM INF SSH Connection failed, retrying in 10 seconds... (Attempt 1/5)

**Comment by Morishiri** [comment]
Hello.

The issues should be resolved. Please try again.
