### ISSUE TITLE
TLS Certificate failed to provision.

### ISSUE THREAD

**Issue by sinmichael** [loophole/cli#219]
**Describe the bug**
Got an error **TLS Certificate failed to provision. Will be obtained with first request made by any client, therefore first execution may be slower**. I tried restarting the command line and restarting Windows.

**To Reproduce**
1. Run loophole http 3000 -v
2. Go to URL
3. See error

**Expected behavior**
TLS Certificate gets provisioned.

**Screenshots**
3:43PM DBG Info response: {1.0.0-beta.15}
Registering your domain...
3:44PM DBG Site registration response: {stan loophole.site}
3:44PM DBG Tunnel starting up...
Starting local TLS proxy server
3:44PM DBG Proxy via http to http://127.0.0.1:3000 created
Starting local proxy server...
3:44PM DBG Server for proxy created

3:44PM DBG Proxy listener for HTTPS started on port 62339

3:44PM DBG Started server TLS server
Initializing secure tunnel...
3:44PM DBG Dialing SSH Gateway for HTTPS succeeded

Forwarding https://xxx.loophole.site -> http://127.0.0.1:3000
Press CTRL + C to stop the service
Logs:
3:44PM INF Awaiting connections...

3:44PM DBG Issuing request to provision certificate

3:44PM DBG For loop cycle

3:44PM DBG Waiting to accept
3:44PM ERR TLS Certificate failed to provision. Will be obtained with first request made by any client, therefore first execution may be slower

**Environment**
 - OS: Windows
 - Version 1.0.0-beta.15

**Comment by JoshuaPotter** [comment]
I'm also experiencing this issue.

**Comment by sachingiri** [comment]
Same issue, now when i am trying to to reproduce it gets stuck after "Initializing secure tunnel".
![Screenshot 2023-03-19 at 1 34 10 PM](https://user-images.githubusercontent.com/19957991/226161973-751faa94-cc52-4ea4-8550-e9b2dc830a9b.png)

**Comment by 0x7f** [comment]
Hey, sorry for the issues you are experiencing. We had an issue with our servers and just fixed them. It should work again. Please let me know if you still running into issues.

**Comment by woshichenghaibo** [comment]
> Registering your domain... Error! Post "https://api.loophole.cloud:443/api/site": dial tcp: lookup api.loophole.cloud: i/o timeout 10:34AM ERR Something unexpected happened, please let developers know 10:34AM FTL Post "https://api.loophole.cloud:443/api/site": dial tcp: lookup api.loophole.cloud: i/o timeout Loophole - End to end TLS encrypted TCP communication between you and your clients

same

**Comment by fbasoco** [comment]
> > Registering your domain... Error! Post "https://api.loophole.cloud:443/api/site": dial tcp: lookup api.loophole.cloud: i/o timeout 10:34AM ERR Something unexpected happened, please let developers know 10:34AM FTL Post "https://api.loophole.cloud:443/api/site": dial tcp: lookup api.loophole.cloud: i/o timeout Loophole - End to end TLS encrypted TCP communication between you and your clients
> 
> same

same
