### ISSUE TITLE
[Bug] x509: certificate has expired or is not yet valid:

### ISSUE THREAD

**Issue by cheejiayuan512** [loophole/cli#240]
Registering your domain... Error! Post "https://api.loophole.cloud:443/api/site": x509: certificate has expired or is not yet valid:
12:23PM ERR Something unexpected happened, please let developers know
12:23PM FTL Post "https://api.loophole.cloud:443/api/site": x509: certificate has expired or is not yet valid:
![image](https://github.com/loophole/cli/assets/13083403/1d953086-86a2-4854-9929-e38b9f8fa9e4)

**Comment by Morishiri** [comment]
Fixed.
