### ISSUE TITLE
 ERR TLS Certificate failed to provision. Will be obtained with first request made by any client, therefore first execution may be slower

### ISSUE THREAD

**Issue by VanceNN** [loophole/cli#241]
**Describe the bug**
Loophole is not starting from today

**To Reproduce**
1. Start cmd
2. Write loophole http 7860
3. See error

**Expected behavior**
Positive result

**Screenshots**
 ERR TLS Certificate failed to provision. Will be obtained with first request made by any client, therefore first execution may be slower

**Environment**
 - OS: Win 10
![image](https://github.com/loophole/cli/assets/62590019/83e206e2-e9c2-45b8-8fbc-111fa42470a5)

**Comment by VanceNN** [comment]
![image](https://github.com/loophole/cli/assets/62590019/d51f0d5a-88f5-43ea-9948-c0552d2ca368)

**Comment by steffen-mueller** [comment]
Same here!

**Comment by SecurityCheck** [comment]
Dito!

**Comment by 0x7f** [comment]
Hey. Sorry for the issues. I will look into it in a moment.

**Comment by steffen-mueller** [comment]
Hey @0x7f , thanks for looking into it. The problem already disappeared after about 60min of service interruption.

**Comment by 0x7f** [comment]
@steffen-mueller glad to hear it is working for you again.

One of the backend services got stuck and I restarted it. Should work for you as well again @SecurityCheck @VanceNN

**Comment by eusoubrasileiro** [comment]
This still keeps happening for me.
