### ISSUE TITLE
??? http: TLS handshake error from 127.0.0.1:39771: local error: tls: bad record MAC

### ISSUE THREAD

**Issue by jesues-ar** [loophole/cli#242]
**Describe the bug**
??? http: TLS handshake error from 127.0.0.1:39771: local error: tls: bad record MAC

**Environment**
 - OS: windows10
 - Version:loophole-cli_1.0.0-beta.15_windows_64bit

**Additional context**
1:54PM INF Succeeded to accept connection over HTTPS
1:54PM INF Succeeded to accept connection over HTTPS
2:37PM INF Succeeded to accept connection over HTTPS
2:47PM INF Succeeded to accept connection over HTTPS
2:47PM INF Succeeded to accept connection over HTTPS
2:49PM INF Succeeded to accept connection over HTTPS
2:56PM ??? http: TLS handshake error from 127.0.0.1:39771: local error: tls: bad record MAC

**Comment by 0x7f** [comment]
Hi @jesues-ar it seems the server was stuck again. Restarted it and should work again. Very sorry that we did not find time yet to provide a permanent fix for this. Hopefully something for the Christmas break :)

**Comment by jesues-ar** [comment]
Thank you, let's work hard together
&nbsp;


飘雪木马
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Maximilian ***@***.***&gt;; 
发送时间: 2023年12月5日(星期二) 下午3:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [loophole/cli] ??? http: TLS handshake error from 127.0.0.1:39771: local error: tls: bad record MAC (Issue #242)






你好@耶稣阿尔看来服务器又卡住了。重新启动了，应该又可以工作了。非常抱歉，我们没有找到时间，尚未提供一个永久性的解决方案。希望圣诞假期的一些东西：）
嗨，@天啊，服务器似乎又卡住了。重新启动它，应该再次工作。非常抱歉，我们还没有找到时间为此提供永久修复。希望圣诞假期能:)

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
你收到这个是因为你被提到了。消息ID:<漏洞/点击/问题/ 242 / ***@***.***和&gt;
