### ISSUE TITLE
SSL Certificate for api.loophole.cloud is expired

### ISSUE THREAD

**Issue by barbolo** [loophole/cli#255]
The SSL certificate has expired today.

```
FTL Post "https://api.loophole.cloud:443/api/site": x509: “api.loophole.cloud” certificate is expired
```

**Comment by sirbootoo** [comment]
Facing the same problem.

**Comment by 0x7f** [comment]
Very sorry about the problem. I'm on vacation and did not notice in time. Just fixed it. Let me know if you still have issues.
