### ISSUE TITLE
CLI is stuck on "Dialing SSH Gateway for HTTPS succeeded" again

### ISSUE THREAD

**Issue by DevonPeroutky** [loophole/cli#258]
**Describe the bug**
I'm having the same issue as #235, where I'm seeing the CLI get stuck after `Dialing SSH Gateway for HTTPS succeeded`.  I have verified my site is running successfully on port 8000.

**To Reproduce**
```loophole http 8000 -v```
Stuck at DBG Dialing SSH Gateway for HTTPS succeeded

**Expected behavior**
To start tunneling

**Screenshots**
![Screenshot 2024-03-08 at 9 47 09 PM](https://github.com/loophole/cli/assets/36947377/fb1b0f91-55d8-4cc5-ab0c-3ddadea337e0)

**Environment**
 - OS: `Debian 5.10.205-2 (2023-12-31) x86_64 GNU/Linux`
 - Version: `loophole version 1.0.0-beta.15 (5cecf33)`

**Additional context**

**Comment by 0x7f** [comment]
Unfortunately, this happens when our backend services are stuck. We are working on an improved version of the backend which should not have this issue. I do not have much time for this, due to lots of work at the paying job, but hope to have it finished soon™️ ;)
