### ISSUE TITLE
(ACCIDENTALLY MADE A DUPLICATE OF AN ALREADY EXISTING ISSUE)

### ISSUE THREAD

**Issue by queenkoopa8500** [loophole/cli#266]
accidentally made a duplicate of an already existing issue which is #249

**Comment by uuphoria2** [comment]
@Morishiri can you or anybody help me on this issue please?

**Comment by uuphoria2** [comment]
this issue is already at #249 closing this

**Comment by uuphoria2** [comment]
accidentally made a duplicate of somebodys already existing issue: #249 go to that issue page instead, loophole team incase you look at this issue (this current one aka #266) instead of #249

**Comment by uuphoria2** [comment]
#249 accidentally made a duplicate of this

**Comment by uuphoria2** [comment]
this is a duplicate of #249 (accidental) go to issue #249 instead for anyone viewing this
