### ISSUE TITLE
Console output messed up on Windows

### ISSUE THREAD

**Issue by 0x7f** [loophole/cli#78]
**Describe the bug**

When starting a loophole on Windows in PowerShell, some output is messed up. Unfortunately the line with loophole name (luckily i figured the name by checking the certificate name in `~/.loophole/certs/`). Might make sense to ensure logs are always printed sequentially.

```
F11:49oArMward inINFg  Issuhitntgps r:eq/u/e4sbt9 36e886btf7bb123abbb8o264c2daee7.lo ophole.hpostro -> vi.sio
n Press CTRL + C to stop cthe servicee
r
tLogs:i
ficnect11:49AM INF Awaiting connections...
```

**To Reproduce**
Run `loophole path .` in Windows PowerShell.

**Expected behavior**

No messed up output.

**Screenshots**

See log output above

**Environment**
 - OS: Windows 10
 - Version 1.0.0-beta.11

**Additional context**
N/A

**Comment by Morishiri** [comment]
The same happens on regular cmd:
![fail1](https://user-images.githubusercontent.com/11832884/102480540-b43f0880-4060-11eb-8de0-ea8000d11eda.png)
![fail2](https://user-images.githubusercontent.com/11832884/102480524-aee1be00-4060-11eb-9d00-fd84971df83f.png)
