### ISSUE TITLE
Fetching the certificate makes the current "ConnectionOccured" check for the feedback prompt useless

### ISSUE THREAD

**Issue by denny241** [loophole/cli#82]
**Describe the bug**
Since we automatically establish a connection on startup, the previous check for the occurence of a valid connection will now always be set to true as soon as the tunnel is accessible instead of when the user first used it successfully.

**To Reproduce**
1. Start a tunnel
2. Close the connection without connecting first
3. See the feedback form link that was initially designed to only be displayed after a successful user interaction

**Expected behavior**
Only show the link when someone other than the cli connected to the tunnel (eg. check for more than 1 occured connection instead of any connections at all)

**Environment**
 - OS: Ubuntu 20.04
 - Commit 5f3291e

**Comment by Morishiri** [comment]
This is already done some time ago.
