### ISSUE TITLE
allow for specific url path

### ISSUE THREAD

**Issue by AdamJel** [loophole/cli#91]
Now, it possible to specify port and host, but not additional path on that port.

Example: For minikube dashboard, the generated url is `http://127.0.0.1:65278/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/`.

This should be possible to specify for the `loophole http`. Either to put it directly to port: `loophole http 65278/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ 127.0.0.1`, or to add third option:  `loophole http <port> [host] [path] [flags]`.

Also, it could be more user friendly to specify host and port as ther are: `loophole http <host:port/path> [flags]`.

**Comment by Morishiri** [comment]
I think it's really good feature idea :)

**Comment by Morishiri** [comment]
@AdamJel I implemented the first part of your request and just released it in https://github.com/loophole/cli/releases/tag/1.0.0-beta.14. About specifying `<host:port/path>` we will introduce some changes to that in the future. Right now it's used with `loophole <port> [host] --path <path>` flag.
